import type { StylesConfig } from '@/app/types';

// 样式配置 - 8 个公众号样式主题
export const STYLES: StylesConfig = {
  'wechat-default': {
    name: '默认公众号风格',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.8 !important; color: #3f3f3f !important; word-wrap: break-word;',
      h1: 'font-size: 24px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 2px solid #1a73b5;',
      h2: 'font-size: 22px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 4px solid #1a73b5;',
      h3: 'font-size: 20px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      h4: 'font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h5: 'font-size: 17px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 18px 0 9px;',
      h6: 'font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 16px 0 8px;',
      p: 'margin: 16px 0 !important; line-height: 1.8 !important; color: #3f3f3f !important;',
      strong: 'font-weight: 600; color: #2c3e50 !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #1a73b5 !important; text-decoration: none; border-bottom: 1px solid #1a73b5;',
      ul: 'margin: 16px 0; padding-left: 24px;',
      ol: 'margin: 16px 0; padding-left: 24px;',
      li: 'margin: 8px 0; line-height: 1.8 !important;',
      blockquote: 'margin: 16px 0; padding: 8px 16px; background-color: #fafafa !important; border-left: 3px solid #999; color: #666 !important; line-height: 1.5 !important;',
      code: 'font-family: Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #c0392b !important; border-radius: 3px;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #2d2d2d !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 32px 0; border: none; border-top: 1px solid #e0e0e0;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 20px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0f0f0 !important; padding: 10px; text-align: left; border: 1px solid #e0e0e0; font-weight: 600;',
      td: 'padding: 10px; border: 1px solid #e0e0e0;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'wechat-anthropic': {
    name: 'Claude',
    styles: {
      container: 'max-width: 700px; margin: 0 auto; padding: 20px 24px 40px 24px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.75 !important; color: #2b2b2b !important; word-wrap: break-word; letter-spacing: -0.01em;',
      h1: 'font-size: 32px; font-weight: 600; color: #A8522C !important; line-height: 1.2 !important; margin: 36px 0 18px; letter-spacing: -0.02em;',
      h2: 'font-size: 26px; font-weight: 600; color: #A8522C !important; line-height: 1.25 !important; margin: 32px 0 16px; letter-spacing: -0.015em;',
      h3: 'font-size: 22px; font-weight: 600; color: #2b2b2b !important; line-height: 1.3 !important; margin: 28px 0 14px; letter-spacing: -0.01em;',
      h4: 'font-size: 19px; font-weight: 600; color: #3a3a3a !important; line-height: 1.35 !important; margin: 24px 0 12px; letter-spacing: -0.01em;',
      h5: 'font-size: 17px; font-weight: 600; color: #4a4a4a !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h6: 'font-size: 16px; font-weight: 600; color: #5a5a5a !important; line-height: 1.45 !important; margin: 18px 0 9px;',
      p: 'margin: 20px 0 !important; line-height: 1.8 !important; color: #2b2b2b !important; font-size: 15px; letter-spacing: -0.005em;',
      strong: 'font-weight: 600; color: #A8522C !important; background-color: rgba(168, 82, 44, 0.08) !important; padding: 2px 6px; border-radius: 3px;',
      em: 'font-style: italic; color: #5a5a5a !important;',
      a: 'color: #A8522C !important; text-decoration: none; border-bottom: 1px solid rgba(168, 82, 44, 0.4); font-weight: 500;',
      ul: 'margin: 20px 0; padding-left: 28px;',
      ol: 'margin: 20px 0; padding-left: 28px;',
      li: 'margin: 10px 0; line-height: 1.8 !important; color: #2b2b2b !important; font-size: 15px;',
      blockquote: 'margin: 18px 0; padding: 10px 16px; background-color: rgba(168, 82, 44, 0.06) !important; border-left: 4px solid #A8522C; color: #2b2b2b !important; font-size: 15px; line-height: 1.6 !important; font-style: italic; border-radius: 6px;',
      code: 'font-family: "SF Mono", Consolas, Monaco, monospace; font-size: 14px; padding: 2px 6px; background-color: rgba(168, 82, 44, 0.08) !important; color: #A8522C !important; border-radius: 6px; font-weight: 500; border: 1px solid rgba(168, 82, 44, 0.15);',
      pre: 'margin: 24px 0; padding: 20px; background-color: #2d2d2d !important; color: #f5f5f5 !important; border-radius: 10px; overflow-x: auto; line-height: 1.55 !important;',
      hr: 'margin: 36px auto; border: none; height: 2px; background-color: rgba(168, 82, 44, 0.3) !important; max-width: 200px;',
      img: 'max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto; border-radius: 10px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px; border-radius: 8px; overflow: hidden;',
      th: 'background-color: rgba(168, 82, 44, 0.08) !important; padding: 12px 16px; text-align: left; border: none; font-weight: 600; color: #2b2b2b !important; border-bottom: 2px solid rgba(168, 82, 44, 0.2);',
      td: 'padding: 12px 16px; border: none; border-bottom: 1px solid rgba(168, 82, 44, 0.1); color: #2b2b2b !important;',
      tr: 'border: none;',
    }
  },

  'wechat-tech': {
    name: '技术风格',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 20px 20px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.75 !important; color: #2c3e50 !important; word-wrap: break-word;',
      h1: 'font-size: 26px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 36px 0 18px; padding: 0 0 12px; border-bottom: 3px solid #0066cc;',
      h2: 'font-size: 22px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 32px 0 16px; padding-left: 16px; padding-top: 4px; padding-bottom: 4px; border-left: 5px solid #00a67d; background-color: #f0f9ff !important;',
      h3: 'font-size: 20px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 3px solid #ff9800;',
      h4: 'font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      h5: 'font-size: 17px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h6: 'font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 18px 0 9px;',
      p: 'margin: 18px 0 !important; line-height: 1.8 !important; color: #3a3a3a !important;',
      strong: 'font-weight: 700; color: #1a1a1a !important; background-color: #fff3cd !important; padding: 2px 4px; border-radius: 8px;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc;',
      ul: 'margin: 18px 0; padding-left: 28px;',
      ol: 'margin: 18px 0; padding-left: 28px;',
      li: 'margin: 10px 0; line-height: 1.8 !important; color: #3a3a3a !important;',
      blockquote: 'margin: 16px 0; padding: 8px 16px; background-color: #f5f9fc !important; border-left: 3px solid #2196f3; color: #555 !important; line-height: 1.5 !important;',
      code: 'font-family: "Fira Code", Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 3px 6px; background-color: #ffe6e6 !important; color: #c0392b !important; border-radius: 8px; font-weight: 500;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1e1e1e !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 36px 0; border: none; height: 2px; background-color: #0066cc !important;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #0066cc !important; color: #fff !important; padding: 12px; text-align: left; border: 1px solid #0052a3; font-weight: 600;',
      td: 'padding: 12px; border: 1px solid #e0e0e0; background-color: #fff !important;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'wechat-elegant': {
    name: '优雅简约',
    styles: {
      container: 'max-width: 720px; margin: 0 auto; padding: 12px 20px 30px 20px; font-family: "Songti SC", "SimSun", Georgia, serif; font-size: 15px; line-height: 1.85 !important; color: #333 !important; word-wrap: break-word;',
      h1: 'font-size: 26px; font-weight: 400; color: #1a1a1a !important; line-height: 1.4 !important; margin: 36px 0 18px; text-align: center; letter-spacing: 2px;',
      h2: 'font-size: 22px; font-weight: 400; color: #2c2c2c !important; line-height: 1.45 !important; margin: 32px 0 16px; text-align: center; letter-spacing: 1px;',
      h3: 'font-size: 19px; font-weight: 400; color: #3a3a3a !important; line-height: 1.5 !important; margin: 28px 0 14px; letter-spacing: 0.5px;',
      h4: 'font-size: 17px; font-weight: 400; color: #444 !important; line-height: 1.55 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 400; color: #555 !important; line-height: 1.55 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 400; color: #666 !important; line-height: 1.55 !important; margin: 18px 0 9px;',
      p: 'margin: 18px 0 !important; line-height: 1.85 !important; color: #444 !important; text-indent: 2em; letter-spacing: 0.5px;',
      strong: 'font-weight: 600; color: #1a1a1a !important;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #7a6348 !important; text-decoration: none; border-bottom: 1px dotted #7a6348;',
      ul: 'margin: 18px 0; padding-left: 28px;',
      ol: 'margin: 18px 0; padding-left: 28px;',
      li: 'margin: 10px 0; line-height: 1.85 !important;',
      blockquote: 'margin: 18px auto; padding: 10px 20px; background-color: transparent !important; border-left: 2px solid #ccc; color: #666 !important; max-width: 600px; line-height: 1.6 !important;',
      code: 'font-family: Menlo, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #8b4513 !important; border-radius: 3px;',
      pre: 'margin: 24px 0; padding: 18px; background-color: #f9f9f9 !important; border: 1px solid #e5e5e5; border-radius: 8px; overflow-x: auto; line-height: 1.7 !important;',
      hr: 'margin: 36px auto; border: none; text-align: center; height: 1px; background-color: #e0e0e0 !important; max-width: 200px;',
      img: 'max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f8f8f8 !important; padding: 10px; text-align: left; border-bottom: 2px solid #d0d0d0; font-weight: 400; color: #555 !important;',
      td: 'padding: 10px; border-bottom: 1px solid #e5e5e5;',
      tr: 'border-bottom: 1px solid #e5e5e5;',
    }
  },

  // === 原研哉设计 ===

  'hische-editorial': {
    name: 'Hische·编辑部',
    styles: {
      container: 'max-width: 700px; margin: 0 auto; padding: 20px 20px 50px 20px; font-family: "Crimson Text", Garamond, "Songti SC", "STSong", "SimSun", serif; font-size: 15px; line-height: 1.75 !important; color: #2c2c2c !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 400; color: #c9302c !important; line-height: 1.2 !important; margin: 36px 0 18px; letter-spacing: -0.02em; font-family: "Bodoni MT", "Didot", "Songti SC", "STSong", serif; text-align: center;',
      h2: 'font-size: 26px; font-weight: 400; color: #2c2c2c !important; line-height: 1.25 !important; margin: 32px 0 16px; letter-spacing: -0.015em; font-family: "Bodoni MT", "Didot", "Songti SC", "STSong", serif; border-top: 1px solid #c9302c; border-bottom: 1px solid #c9302c; padding: 10px 0; text-align: center;',
      h3: 'font-size: 21px; font-weight: 400; color: #2c2c2c !important; line-height: 1.3 !important; margin: 28px 0 14px; font-family: "Bodoni MT", "Didot", "Songti SC", "STSong", serif;',
      h4: 'font-size: 17px; font-weight: 600; color: #2c2c2c !important; line-height: 1.35 !important; margin: 24px 0 12px; text-transform: uppercase; letter-spacing: 0.05em;',
      h5: 'font-size: 16px; font-weight: 400; color: #2c2c2c !important; line-height: 1.4 !important; margin: 20px 0 10px; font-style: italic;',
      h6: 'font-size: 15px; font-weight: 400; color: #666 !important; line-height: 1.45 !important; margin: 18px 0 9px;',
      p: 'margin: 20px 0 !important; line-height: 1.8 !important; color: #2c2c2c !important; text-align: justify;',
      strong: 'font-weight: 700; color: #c9302c !important; letter-spacing: 0.02em;',
      em: 'font-style: italic; color: #2c2c2c !important;',
      a: 'color: #c9302c !important; text-decoration: none; border-bottom: 1px solid #c9302c;',
      ul: 'margin: 20px 0; padding-left: 25px; list-style: disc;',
      ol: 'margin: 20px 0; padding-left: 25px;',
      li: 'margin: 10px 0; line-height: 1.75 !important; color: #2c2c2c !important;',
      blockquote: 'margin: 20px 0; padding: 0 24px; background-color: transparent !important; border-left: none; color: #2c2c2c !important; font-size: 15px; line-height: 1.55 !important; font-style: italic; text-align: center; font-family: "Bodoni MT", "Didot", "Songti SC", "STSong", serif;',
      code: 'font-family: "Courier Prime", monospace; font-size: 14px; padding: 2px 6px; background-color: #f9f9f9 !important; color: #c9302c !important; border: 1px solid #e0e0e0;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f9f9f9 !important; border-left: 4px solid #c9302c; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #c9302c !important; max-width: 100px;',
      img: 'max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto; border: 1px solid #e0e0e0;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f9f9f9 !important; padding: 10px 12px; text-align: left; border-top: 2px solid #c9302c; border-bottom: 2px solid #c9302c; font-weight: 700; color: #2c2c2c !important; text-transform: uppercase; letter-spacing: 0.05em; font-size: 14px;',
      td: 'padding: 10px 12px; border-bottom: 1px solid #e0e0e0; color: #2c2c2c !important;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  // === 建筑大师跨界设计 ===

  // === 国际媒体风格 ===


  'sspai-geek': {
    name: '少数派·极客',
    styles: {
      container: 'max-width: 720px; margin: 0 auto; padding: 20px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #1a1a1a !important; word-wrap: break-word;',
      h1: 'font-size: 22px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 36px 0 18px; padding-bottom: 10px; border-bottom: 2px solid #2e6e9e;',
      h2: 'font-size: 19px; font-weight: 700; color: #2e6e9e !important; line-height: 1.35 !important; margin: 32px 0 16px; padding-left: 12px; border-left: 3px solid #2e6e9e;',
      h3: 'font-size: 17px; font-weight: 700; color: #2e6e9e !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 16px; font-weight: 700; color: #1a1a1a !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      h5: 'font-size: 16px; font-weight: 700; color: #1a1a1a !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h6: 'font-size: 16px; font-weight: 600; color: #1a1a1a !important; line-height: 1.4 !important; margin: 18px 0 9px;',
      p: 'margin: 16px 0 !important; line-height: 1.75 !important; color: #1a1a1a !important;',
      strong: 'font-weight: 700; color: #2e6e9e !important;',
      em: 'font-style: italic; color: #1a1a1a !important;',
      a: 'color: #2e6e9e !important; text-decoration: none; border-bottom: 1px solid #2e6e9e;',
      ul: 'margin: 16px 0; padding-left: 24px; list-style-type: disc;',
      ol: 'margin: 16px 0; padding-left: 24px; list-style-type: decimal;',
      li: 'margin: 8px 0; line-height: 1.75 !important; color: #1a1a1a !important;',
      blockquote: 'margin: 16px 0; padding: 10px 16px; background-color: #f7f9fc !important; border-left: 3px solid #2e6e9e; color: #1a1a1a !important; line-height: 1.6 !important;',
      code: 'font-family: "SF Mono", Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f0f4f8 !important; color: #2e6e9e !important; border-radius: 3px;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #1e2127 !important; border-radius: 6px; overflow-x: auto; line-height: 1.5 !important;',
      hr: 'margin: 30px 0; border: none; border-top: 1px solid #e0e0e0;',
      img: 'max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 20px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 14px;',
      th: 'background-color: #2e6e9e !important; color: #fff !important; padding: 10px; text-align: left; border: 1px solid #2e6e9e; font-weight: 700;',
      td: 'padding: 10px; border: 1px solid #e0e0e0; color: #1a1a1a !important;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },



  'bauhaus-geometric': {
    name: '包豪斯·几何',
    styles: {
      container: 'max-width: 700px; margin: 0 auto; padding: 20px; font-family: "Helvetica Neue", Arial, sans-serif; font-size: 15px; line-height: 1.75 !important; color: #1a1a1a !important; word-wrap: break-word;',
      h1: 'font-size: 26px; font-weight: 700; color: #1a1a1a !important; line-height: 1.2 !important; margin: 36px 0 18px; text-transform: uppercase; letter-spacing: 0.1em; padding-bottom: 10px; border-bottom: 4px solid #c0392b;',
      h2: 'font-size: 20px; font-weight: 700; color: #c0392b !important; line-height: 1.3 !important; margin: 32px 0 16px; letter-spacing: 0.05em;',
      h3: 'font-size: 17px; font-weight: 700; color: #1a6aa5 !important; line-height: 1.35 !important; margin: 28px 0 14px;',
      h4: 'font-size: 16px; font-weight: 700; color: #1a1a1a !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      h5: 'font-size: 15px; font-weight: 700; color: #1a1a1a !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h6: 'font-size: 15px; font-weight: 600; color: #1a1a1a !important; line-height: 1.4 !important; margin: 18px 0 9px;',
      p: 'margin: 16px 0 !important; line-height: 1.75 !important; color: #1a1a1a !important;',
      strong: 'font-weight: 700; color: #c0392b !important;',
      em: 'font-style: italic; color: #1a1a1a !important;',
      a: 'color: #1a6aa5 !important; text-decoration: none; border-bottom: 2px solid #1a6aa5;',
      ul: 'margin: 16px 0; padding-left: 24px; list-style-type: square;',
      ol: 'margin: 16px 0; padding-left: 24px; list-style-type: decimal;',
      li: 'margin: 8px 0; line-height: 1.75 !important; color: #1a1a1a !important;',
      blockquote: 'margin: 16px 0; padding: 12px 16px; background-color: #fffdf0 !important; border-left: 5px solid #f1c40f; color: #1a1a1a !important; line-height: 1.6 !important;',
      code: 'font-family: Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #1a6aa5 !important;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #1a1a1a !important; color: #fff !important; overflow-x: auto; line-height: 1.5 !important;',
      hr: 'margin: 30px 0; border: none; height: 4px; background-color: #1a1a1a !important;',
      img: 'max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 20px auto;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 14px;',
      th: 'background-color: #c0392b !important; color: #fff !important; padding: 10px; text-align: left; border: 1px solid #c0392b; font-weight: 700;',
      td: 'padding: 10px; border: 1px solid #ddd; color: #1a1a1a !important;',
      tr: 'border-bottom: 1px solid #ddd;',
    }
  },

  'baoyu-ai': {
    name: '宝玉AI',
    styles: {
      container: 'max-width: 677px; margin: 0 auto; padding: 0 8px; font-family: "PingFang SC", -apple-system-font, system-ui, "Helvetica Neue", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 14px; line-height: 1.75 !important; color: #3f3f3f !important; word-wrap: break-word; text-align: justify;',
      h1: 'font-size: 22px; font-weight: 500; color: rgba(0,0,0,0.9) !important; line-height: 1.4 !important; margin: 0 0 14px; letter-spacing: 0.544px;',
      h2: 'font-size: 17px; font-weight: 700; color: #fff !important; line-height: 1.75 !important; margin: 64px auto 32px; padding: 2px 6px; background-color: #0F4C81 !important; display: table; text-align: center; letter-spacing: 0.544px;',
      h3: 'font-size: 16px; font-weight: 700; color: #3f3f3f !important; line-height: 1.2 !important; margin: 32px 8px 12px 0; padding-left: 8px; border-left: 3px solid #0F4C81; letter-spacing: 0.544px;',
      h4: 'font-size: 15px; font-weight: 700; color: #3f3f3f !important; line-height: 1.75 !important; margin: 24px 8px 12px;',
      h5: 'font-size: 15px; font-weight: 600; color: #3f3f3f !important; line-height: 1.75 !important; margin: 20px 8px 10px;',
      h6: 'font-size: 14px; font-weight: 600; color: #3f3f3f !important; line-height: 1.75 !important; margin: 18px 8px 9px;',
      p: 'margin: 24px 8px !important; line-height: 1.75 !important; color: #3f3f3f !important; letter-spacing: 1px; text-align: left; font-size: 14px;',
      strong: 'font-weight: 700; color: #0F4C81 !important;',
      em: 'font-style: italic; color: #3f3f3f !important;',
      a: 'color: #0F4C81 !important; text-decoration: none; border-bottom: 1px solid #0F4C81;',
      ul: 'margin: 0; padding-left: 16px; list-style-type: circle;',
      ol: 'margin: 0; padding-left: 16px; list-style-type: decimal;',
      li: 'margin: 3.2px 8px; line-height: 1.75 !important; color: #3f3f3f !important; letter-spacing: 0.544px; font-size: 14px;',
      blockquote: 'margin: 0 0 15px; padding: 15px; background-color: #f7f7f7 !important; border-left: 4px solid #0F4C81; color: #3f3f3f !important; font-size: 14px; line-height: 1.75 !important;',
      code: 'font-family: Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #0F4C81 !important; border-radius: 3px;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #2d2d2d !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 24px 0; border: none; border-top: 1px solid rgba(0,0,0,0.1);',
      img: 'max-width: 100%; height: auto; display: block; margin: 20px auto;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #0F4C81 !important; color: #fff !important; padding: 10px; text-align: left; border: 1px solid #0F4C81; font-weight: 600;',
      td: 'padding: 10px; border: 1px solid #e0e0e0; color: #3f3f3f !important;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

};
